### ISSUE TITLE
1월 17일 발견한 버그 (해결 안됨)

### ISSUE THREAD

**Issue by bestowing** [rotmdwo/ChattingApp#1]
1. 상태메세지 입력시 업데이트 적용 안됨.
2. 모든 액티비티가 finish되어서 뒤로가기 버튼 입력시 MainActivity로 이동함.

**Comment by rotmdwo** [comment]
1. 데이터베이스에 임의로 넣은 패스워드가 String이 아닌 Int로 저장되어 있어서 (" "가 없는 문제) 에러가 났었던 것이었고, 비밀번호를 String으로 수정했더니 상태메세지 업데이트가 잘 작동되었습니다.

2. MainActivity(로딩창)에서 화면을 넘어가면서 로딩창을 finish() 함으로써 문제를 해결하였습니다.
